{
 "title": "Worker",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Worker stale recovered total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(integration_worker_stale_recovered_total{job=\"integration-worker\"}[1h])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker heartbeat age",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - integration_worker_last_heartbeat_unixtime{job=\"integration-worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker idle cycles rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(integration_worker_idle_cycles_total{job=\"integration-worker\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker cycles rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(integration_worker_cycles_total{job=\"integration-worker\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker picked events rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(integration_worker_events_picked_total{job=\"integration-worker\"}[5m]) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker processing duration p95",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(integration_worker_processing_duration_seconds_bucket{job=\"integration-worker\"}[5m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker processed results",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (result) (\r\n  rate(integration_worker_events_processed_total{job=\"integration-worker\"}[5m])\r\n) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}