{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Fiscal messages",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"fiscal_poller\"} |= \"fiscal\""
    }
   ]
  },
  {
   "title": "API logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"api\"}"
    }
   ]
  },
  {
   "title": "API webhook logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"api\"} |= \"webhook\""
    }
   ]
  },
  {
   "title": "Fiscal poller logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"fiscal_poller\"}"
    }
   ]
  },
  {
   "title": "Worker failed messages",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"worker\"} |= \"FAILED\""
    }
   ]
  },
  {
   "title": "Worker logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"worker\"}"
    }
   ]
  },
  {
   "title": "All errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"integration-.*-logs\", level=\"ERROR\"}"
    }
   ]
  }
 ]
}